Adding feature to scredule a root partition resize on next boot #231

diff --git a/kano-updater b/kano-updater
--- a/kano-updater
+++ b/kano-updater
@@ -1,4 +1,7 @@
 #!/bin/bash
+#
+#  Updates system packages, expands root partition if needed
+#
 
 function update()
 {
@@ -6,6 +9,11 @@ function update()
    sudo apt-get -y dist-upgrade
    sudo apt-get -y autoremove
    sudo apt-get -y autoclean
+}
+
+function expand()
+{
+   sudo /usr/bin/expand-rootfs
 }
 
 # Check for internet connection
@@ -16,7 +24,24 @@ if [ $RESULT != 0 ]; then
   exit 1
 fi
 
-# Call the update function and capture the PID
+# Resize the root partition if needed, then
+# call the update function and capture the PID
+expand
+rc=$?
+if [ $rc -eq 0 ]; then
+   zenity --info --text="Disk partition scheduled for resize\nThe system will reboot now.\nSee you in 2 mins!"
+   sudo /sbin/reboot
+   exit 0
+else
+   if [ $rc -eq 1 ]; then
+     echo "disk partition has already been resized - continuing with updates"
+   else
+     echo "error resizing root file system rc=$rc - continuing with updates"
+   fi
+fi
+
+# Ask for system package upgrades
+# then follow progress with Zenity dialog
 update &
 PID=$!
 
