Added firmware update to kano-updater, and other enhancements https://github.com/KanoComputing/Spindle/issues/318

diff --git a/kano-updater b/kano-updater
--- a/kano-updater
+++ b/kano-updater
@@ -5,10 +5,22 @@
 # Copyright (C) 2013 Kano Computing Ltd.
 # License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
 #
-# Updates system packages, expands root partition if needed
+# Updates system packages and firmware, expands root partition if needed
 #
 
 source /usr/bin/make-common
+
+# Wait on infinite loop until PS has died
+function waitTillPSEnds()
+{
+  while true; do
+    if ! ps -p $1 > /dev/null 2>&1; then
+      break
+    else
+      sleep 1
+    fi
+  done
+}
 
 function update()
 {
@@ -23,23 +35,33 @@ function expand()
    sudo /usr/bin/expand-rootfs
 }
 
+function updateFirmware()
+{
+  sudo rpi-update
+}
+
+
+# Check for root priviledges
+if [ `id -u` -ne 0 ]; then
+  echo "Error: kano-updater must be executed with root privileges" 1>&2
+  exit 1
+fi
+
 # Close open projects
 restart_daemons
 
 # Check for internet connection
 ping -q www.google.com -c 1 &> /dev/null
-RESULT=$?
+INTERNET_ON=$?
+UPDATED=2
 
-if [ $RESULT != 0 ]; then
-  zenity --text="Please connect to the Internet first" --info
-
-else
+if [ $INTERNET_ON -eq 0 ]; then
   # Ask for system package upgrades
   # then follow progress with Zenity dialog
   update &
   PID=$!
-
-  # progress dialog and give focus
+  UPDATED=0
+  # progress dialog
   (
   for I in {0..99..1}; do
     sleep 2
@@ -47,40 +69,62 @@ else
     if ! ps -p $PID > /dev/null 2>&1; then
         # the update is ready
         echo "99"
-        echo "#Ready"
-        sleep 3
         break
     fi
     echo "$I"
   done
   
+  waitTillPSEnds $PID
+  echo "#Ready"
+  sleep 1
   echo "100"
   ) |
   zenity --progress --no-cancel --text="Updating Kanux..." --width=300 --height=90 --auto-close --auto-kill
-
-  # Make sure we don't check partition resizing
-  # until update has finished
-  while true; do
-    if ! ps -p $PID > /dev/null 2>&1; then
-      break
-    else
-      sleep 1
-    fi
-  done
 fi
 
 # Resize the root partition if needed
 expand
 rc=$?
 if [ $rc -eq 0 ]; then
-   zenity --info --text="Disk partition scheduled for resize\nThe system will reboot now.\nSee you in 2 mins!"
-   sudo /sbin/reboot
-# else
-#   if [ $rc -eq 1 ]; then
-#     echo "disk partition has already been resized - continuing with updates"
-#   else
-#     echo "error resizing root file system rc=$rc - continuing with updates"
-#   fi
+  UPDATED=1
+  zenity --info --text="Disk partition scheduled for resize\nThe system will reboot now.\nSee you in 2 mins!"
+  sudo /sbin/reboot
+  exit 0
+# Check for a firmware update 
+# if disk partition has already been resized and there is internet
+elif [ $rc -eq 1 ] && [ $INTERNET_ON -eq 0 ]; then
+
+  # Ask for firmware update
+  # then follow progress with Zenity dialog
+  updateFirmware &
+  PID=$!
+  UPDATED=0
+  # progress dialog
+  (
+  for I in {0..99..1}; do
+    sleep 3
+    # Check if the Firmware Update process is still alive
+    if ! ps -p $PID > /dev/null 2>&1; then
+        # the update is ready
+        echo "99"
+        break
+    fi
+    echo "$I"
+  done
+  
+  waitTillPSEnds $PID
+  echo "#Ready"
+  sleep 1
+  echo "100"
+  ) |
+  zenity --progress --no-cancel --text="Updating firmware..." --width=300 --height=90 --auto-close --auto-kill
+fi
+
+# Update has finished
+if [ $UPDATED -eq 0 ]; then
+  zenity --text="Kanux successfully updated. Thank you!" --info
+elif [ $INTERNET_ON -eq 2 ]; then
+  zenity --text="Please connect to the Internet first" --info
 fi
 
 exit 0
